const demoAssets = {
  recLeague: {
    raw: "/media/rec_league_raw_15s.mp4",
    poster: "/media/rec_league_poster.jpg",
    rawTitle: "Raw rec-league clip",
    roi: [
      [0, 360],
      [640, 360],
      [430, 170],
      [160, 170],
    ],
    note: "Rec-league sample loaded. Live masks are generated by YOLO-Seg ONNX in this browser.",
  },
  pickup5v5: {
    raw: "/media/pickup_5v5_raw_12s.mp4",
    poster: "/media/pickup_5v5_poster.jpg",
    rawTitle: "Raw pickup 5v5 clip",
    roi: [
      [13, 72],
      [627, 72],
      [627, 209],
      [13, 209],
    ],
    note: "Pickup 5v5 sample loaded. Live masks are generated by YOLO-Seg ONNX in this browser.",
  },
  streetballPov: {
    raw: "/media/streetball_pov_raw_12s.mp4",
    poster: "/media/streetball_pov_poster.jpg",
    rawTitle: "Raw streetball POV clip",
    roi: [
      [0, 54],
      [640, 54],
      [640, 360],
      [0, 360],
    ],
    note: "Streetball POV sample loaded. Live masks are generated by YOLO-Seg ONNX in this browser.",
  },
};

const state = {
  summary: null,
  source: "sample",
  view: "raw",
  demo: "recLeague",
  uploadedPath: null,
  sourceVideoUrl: demoAssets.recLeague.raw,
  seedPrompt: "basketball players on court",
  yoloSession: null,
  segSession: null,
  segInputSize: 320,
  segBackend: "WASM fallback",
  browserTracking: false,
  browserTrackHandle: null,
  browserTracks: [],
  nextBrowserTrackId: 0,
};

const byId = (id) => document.getElementById(id);

function fmt(value, digits = 2) {
  if (value === undefined || value === null || Number.isNaN(Number(value))) return "n/a";
  return Number(value).toFixed(digits);
}

function setText(id, value) {
  const node = byId(id);
  if (node) node.textContent = value;
}

function setRunState(value) {
  setText("run-state", value);
}

function setLog(message) {
  setText("benchmark-log", message);
}

function currentDemo() {
  return demoAssets[state.demo] || demoAssets.recLeague;
}

function setVideo(src, title = "Video input", poster = "") {
  stopBrowserMaskTracking(false);
  const video = byId("demo-video");
  const iframe = byId("youtube-frame");
  const canvas = byId("browser-canvas");
  const currentTime = Number.isFinite(video.currentTime) ? video.currentTime : 0;
  iframe.hidden = true;
  canvas.hidden = true;
  video.hidden = false;
  video.poster = poster;
  if (video.currentSrc !== new URL(src, window.location.href).href) {
    video.src = src;
    video.addEventListener(
      "loadedmetadata",
      () => {
        video.currentTime = Math.min(currentTime, Math.max(0, video.duration - 0.2));
      },
      { once: true },
    );
  }
  state.sourceVideoUrl = src;
  setText("feed-title", title);
}

function setDemo(demoKey) {
  if (!demoAssets[demoKey]) return;
  state.demo = demoKey;
  document.querySelectorAll(".demo-option").forEach((button) => {
    button.classList.toggle("active", button.dataset.demo === demoKey);
  });
  if (state.source !== "sample") {
    setSource("sample");
    return;
  }
  setView(state.view);
  setLog(currentDemo().note);
}

function setSource(source) {
  state.source = source;
  document.querySelectorAll(".source-tab").forEach((button) => {
    button.classList.toggle("active", button.dataset.source === source);
  });
  byId("youtube-controls").hidden = source !== "youtube";
  byId("drop-zone").style.display = source === "youtube" ? "none" : "flex";
  const processUpload = byId("process-upload");
  if (processUpload) processUpload.disabled = source !== "upload" || !state.uploadedPath;
  document.querySelectorAll(".view-button").forEach((button) => {
    button.disabled = source !== "sample";
  });

  if (source === "sample") {
    setRunState("Ready");
    setView(state.view);
    setLog(currentDemo().note);
  } else if (source === "youtube") {
    setRunState("Embed mode");
    setLog("Paste a YouTube URL to embed it for review. Browser inference is disabled for YouTube frames because they are cross-origin.");
  } else {
    setRunState("Upload mode");
    if (!state.uploadedPath) {
      setLog("Choose an MP4/WebM file to preview, then analyze a frame or run live browser masks.");
    }
  }
}

function setView(view) {
  state.view = view;
  document.querySelectorAll(".view-button").forEach((button) => {
    button.classList.toggle("active", button.dataset.view === view);
  });
  if (state.source === "sample") {
    const demo = currentDemo();
    if (view === "mask") {
      setVideo(demo.raw, demo.rawTitle, demo.poster);
      startBrowserMaskTracking();
    } else {
      stopBrowserMaskTracking(true);
      setVideo(demo.raw, demo.rawTitle, demo.poster);
    }
  }
}

function youtubeEmbedUrl(rawUrl) {
  let parsed;
  try {
    parsed = new URL(rawUrl.trim());
  } catch {
    return null;
  }
  let id = "";
  if (parsed.hostname.includes("youtu.be")) {
    id = parsed.pathname.replace("/", "");
  } else if (parsed.hostname.includes("youtube.com")) {
    if (parsed.pathname.startsWith("/embed/")) {
      id = parsed.pathname.split("/embed/")[1].split("/")[0];
    } else if (parsed.pathname.startsWith("/shorts/")) {
      id = parsed.pathname.split("/shorts/")[1].split("/")[0];
    } else {
      id = parsed.searchParams.get("v") || "";
    }
  }
  return id ? `https://www.youtube.com/embed/${encodeURIComponent(id)}` : null;
}

function loadYouTube() {
  const url = byId("youtube-url").value;
  const embed = youtubeEmbedUrl(url);
  if (!embed) {
    setLog("That does not look like a YouTube watch, shorts, youtu.be, or embed URL.");
    return;
  }
  const video = byId("demo-video");
  const canvas = byId("browser-canvas");
  const iframe = byId("youtube-frame");
  video.hidden = true;
  canvas.hidden = true;
  iframe.hidden = false;
  iframe.src = embed;
  setText("feed-title", "Embedded YouTube clip");
  setRunState("YouTube loaded");
  setLog("YouTube clip embedded. Use it for visual review or upload a local clip to run model inference.");
}

async function processUploadOnServer() {
  if (!state.uploadedPath) {
    setLog("Choose a local video before running browser mask tracking.");
    return;
  }
  const button = byId("process-upload");
  button.disabled = true;
  setRunState("Rendering");
    setLog(`Running local preview preparation using seed prompt: "${state.seedPrompt}"`);
  try {
    const response = await fetch("/api/process-upload", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ video: state.uploadedPath, max_frames: 180, prompt: state.seedPrompt }),
    });
    const payload = await response.json();
    if (!response.ok) throw new Error("processing failed");
    setVideo(payload.output_video, "Local preview overlay");
    const metrics = payload.metrics;
    setRunState("Preview ready");
    setLog(`Local preview complete. ${fmt(metrics.processing_fps)} FPS CPU preview, ${fmt(metrics.active_frame_pct, 1)}% active frames.`);
  } catch {
    setRunState("Upload mode");
    setLog("Local preview could not finish for this clip. Try a shorter MP4/WebM or analyze a frame in the browser.");
  } finally {
    button.disabled = false;
  }
}

async function uploadFile(file) {
  const objectUrl = URL.createObjectURL(file);
  setSource("upload");
  setVideo(objectUrl, file.name);
  setRunState("Video selected");
  byId("upload-caption").textContent = `${file.name} is ready.`;
    setLog("Local preview ready. Analyze the current frame or run live browser mask tracking.");
  setText("upload-command", "Uploading clip to prepare a reproducible local command.");

  const form = new FormData();
  form.append("video", file);
  try {
    const response = await fetch("/api/upload", { method: "POST", body: form });
    const payload = await response.json();
    if (!response.ok) throw new Error("upload failed");
    state.uploadedPath = payload.path;
    const processUpload = byId("process-upload");
    if (processUpload) processUpload.disabled = false;
    setText("upload-command", `${payload.command.join(" ")} --categories "${state.seedPrompt}"`);
  } catch {
    setText("upload-command", "Server upload is unavailable. Browser frame analysis can still run on the selected local video.");
  }
}

function letterboxToTensor(source, size = 480) {
  const scratch = document.createElement("canvas");
  scratch.width = size;
  scratch.height = size;
  const ctx = scratch.getContext("2d", { willReadFrequently: true });
  ctx.fillStyle = "rgb(114,114,114)";
  ctx.fillRect(0, 0, size, size);
  const srcW = source.videoWidth || source.width;
  const srcH = source.videoHeight || source.height;
  const scale = Math.min(size / srcW, size / srcH);
  const drawW = Math.round(srcW * scale);
  const drawH = Math.round(srcH * scale);
  const padX = Math.floor((size - drawW) / 2);
  const padY = Math.floor((size - drawH) / 2);
  ctx.drawImage(source, padX, padY, drawW, drawH);
  const { data } = ctx.getImageData(0, 0, size, size);
  const tensor = new Float32Array(3 * size * size);
  for (let i = 0, px = 0; i < data.length; i += 4, px += 1) {
    tensor[px] = data[i] / 255;
    tensor[size * size + px] = data[i + 1] / 255;
    tensor[2 * size * size + px] = data[i + 2] / 255;
  }
  return { input: new ort.Tensor("float32", tensor, [1, 3, size, size]), scale, padX, padY };
}

function parseYoloNms(output, transform, width, height, minConf = 0.28) {
  const data = output.data;
  const rows = output.dims[output.dims.length - 2] || 300;
  const cols = output.dims[output.dims.length - 1] || 6;
  const detections = [];
  for (let i = 0; i < rows; i += 1) {
    const offset = i * cols;
    const score = Number(data[offset + 4]);
    const cls = Number(data[offset + 5]);
    if (score < minConf || Math.round(cls) !== 0) continue;
    detections.push({
      score,
      x1: Math.max(0, Math.min(width, (Number(data[offset]) - transform.padX) / transform.scale)),
      y1: Math.max(0, Math.min(height, (Number(data[offset + 1]) - transform.padY) / transform.scale)),
      x2: Math.max(0, Math.min(width, (Number(data[offset + 2]) - transform.padX) / transform.scale)),
      y2: Math.max(0, Math.min(height, (Number(data[offset + 3]) - transform.padY) / transform.scale)),
    });
  }
  return detections.slice(0, 12);
}

function sigmoid(value) {
  return 1 / (1 + Math.exp(-value));
}

function boxArea(box) {
  return Math.max(0, box.x2 - box.x1) * Math.max(0, box.y2 - box.y1);
}

function boxIou(a, b) {
  const x1 = Math.max(a.x1, b.x1);
  const y1 = Math.max(a.y1, b.y1);
  const x2 = Math.min(a.x2, b.x2);
  const y2 = Math.min(a.y2, b.y2);
  const inter = Math.max(0, x2 - x1) * Math.max(0, y2 - y1);
  const union = boxArea(a) + boxArea(b) - inter;
  return union > 0 ? inter / union : 0;
}

function centerScore(a, b, width, height) {
  const ax = (a.x1 + a.x2) / 2;
  const ay = (a.y1 + a.y2) / 2;
  const bx = (b.x1 + b.x2) / 2;
  const by = (b.y1 + b.y2) / 2;
  const dist = Math.hypot(ax - bx, ay - by) / Math.max(1, Math.hypot(width, height));
  return 1 - Math.min(1, dist / 0.24);
}

function nmsDetections(detections, limit = 10, threshold = 0.55) {
  const sorted = [...detections].sort((a, b) => b.score - a.score);
  const kept = [];
  for (const det of sorted) {
    if (kept.every((other) => boxIou(det, other) < threshold)) kept.push(det);
    if (kept.length >= limit) break;
  }
  return kept;
}

function pointInPolygon(point, polygon) {
  if (!polygon || polygon.length < 3) return true;
  let inside = false;
  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i, i += 1) {
    const xi = polygon[i][0];
    const yi = polygon[i][1];
    const xj = polygon[j][0];
    const yj = polygon[j][1];
    const intersects = yi > point.y !== yj > point.y && point.x < ((xj - xi) * (point.y - yi)) / Math.max(1e-6, yj - yi) + xi;
    if (intersects) inside = !inside;
  }
  return inside;
}

function activeRoiForFrame(width, height) {
  if (state.source !== "sample") return null;
  const roi = currentDemo().roi;
  if (!roi) return null;
  return roi.map(([x, y]) => [(x / 640) * width, (y / 360) * height]);
}

function filterSegDetections(detections, width, height) {
  const roi = activeRoiForFrame(width, height);
  return detections.filter((det) => {
    const areaFrac = boxArea(det) / Math.max(1, width * height);
    if (areaFrac < 0.002 || areaFrac > 0.22) return false;
    const foot = { x: (det.x1 + det.x2) / 2, y: det.y2 };
    return pointInPolygon(foot, roi);
  });
}

function decodeSegDetections(detOutput, protoOutput, transform, width, height, minConf = 0.5) {
  const data = detOutput.data;
  const dims = detOutput.dims;
  const channels = dims[1];
  const anchors = dims[2];
  const coeffStart = channels - 32;
  const detections = [];
  for (let anchor = 0; anchor < anchors; anchor += 1) {
    const score = Number(data[(4 + 0) * anchors + anchor]);
    if (score < minConf) continue;
    const cx = Number(data[0 * anchors + anchor]);
    const cy = Number(data[1 * anchors + anchor]);
    const bw = Number(data[2 * anchors + anchor]);
    const bh = Number(data[3 * anchors + anchor]);
    const x1 = Math.max(0, Math.min(width, (cx - bw / 2 - transform.padX) / transform.scale));
    const y1 = Math.max(0, Math.min(height, (cy - bh / 2 - transform.padY) / transform.scale));
    const x2 = Math.max(0, Math.min(width, (cx + bw / 2 - transform.padX) / transform.scale));
    const y2 = Math.max(0, Math.min(height, (cy + bh / 2 - transform.padY) / transform.scale));
    if (x2 <= x1 || y2 <= y1 || boxArea({ x1, y1, x2, y2 }) < width * height * 0.001) continue;
    const coeffs = new Float32Array(32);
    for (let idx = 0; idx < 32; idx += 1) {
      coeffs[idx] = Number(data[(coeffStart + idx) * anchors + anchor]);
    }
    detections.push({ x1, y1, x2, y2, score, coeffs });
  }
  return filterSegDetections(nmsDetections(detections, 10, 0.55), width, height).map((det) => ({
    ...det,
    mask: decodeSegMask(det, protoOutput, transform, width, height),
  }));
}

function decodeSegMask(det, protoOutput, transform, width, height) {
  const proto = protoOutput.data;
  const protoH = protoOutput.dims[2];
  const protoW = protoOutput.dims[3];
  const inputSize = state.segInputSize;
  const stride = inputSize / protoW;
  const mask = new Uint8Array(width * height);
  const x1 = Math.max(0, Math.floor(det.x1));
  const y1 = Math.max(0, Math.floor(det.y1));
  const x2 = Math.min(width - 1, Math.ceil(det.x2));
  const y2 = Math.min(height - 1, Math.ceil(det.y2));
  for (let y = y1; y <= y2; y += 1) {
    const protoY = Math.max(0, Math.min(protoH - 1, Math.floor((y * transform.scale + transform.padY) / stride)));
    for (let x = x1; x <= x2; x += 1) {
      const protoX = Math.max(0, Math.min(protoW - 1, Math.floor((x * transform.scale + transform.padX) / stride)));
      let logit = 0;
      const protoOffset = protoY * protoW + protoX;
      for (let k = 0; k < 32; k += 1) {
        logit += det.coeffs[k] * Number(proto[k * protoH * protoW + protoOffset]);
      }
      if (sigmoid(logit) > 0.52) mask[y * width + x] = 1;
    }
  }
  return mask;
}

function associateBrowserTracks(detections, width, height) {
  const tracks = state.browserTracks.filter((track) => track.misses <= 20);
  const usedTracks = new Set();
  const usedDetections = new Set();
  const associated = [];
  const pairs = [];
  tracks.forEach((track, trackIndex) => {
    detections.forEach((det, detIndex) => {
      const score = 0.68 * boxIou(track, det) + 0.32 * centerScore(track, det, width, height);
      if (score > 0.22) pairs.push({ trackIndex, detIndex, score });
    });
  });
  pairs.sort((a, b) => b.score - a.score);
  pairs.forEach((pair) => {
    if (usedTracks.has(pair.trackIndex) || usedDetections.has(pair.detIndex)) return;
    const track = tracks[pair.trackIndex];
    const det = detections[pair.detIndex];
    associated.push({ ...det, id: track.id, misses: 0, hits: track.hits + 1 });
    usedTracks.add(pair.trackIndex);
    usedDetections.add(pair.detIndex);
  });
  tracks.forEach((track, index) => {
    if (!usedTracks.has(index) && track.misses < 12) associated.push({ ...track, misses: track.misses + 1 });
  });
  detections.forEach((det, index) => {
    if (!usedDetections.has(index)) {
      associated.push({ ...det, id: state.nextBrowserTrackId, misses: 0, hits: 1 });
      state.nextBrowserTrackId += 1;
    }
  });
  state.browserTracks = associated.sort((a, b) => a.id - b.id);
  return state.browserTracks.filter((track) => track.misses <= 1 && track.mask);
}

function drawBrowserOverlay(video, detections, elapsed) {
  const canvas = byId("browser-canvas");
  const ctx = canvas.getContext("2d");
  canvas.width = video.videoWidth;
  canvas.height = video.videoHeight;
  ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
  const palette = [
    [105, 209, 111],
    [111, 191, 224],
    [216, 184, 97],
    [220, 118, 110],
    [172, 140, 232],
    [62, 204, 184],
  ];
  const maskCanvas = document.createElement("canvas");
  maskCanvas.width = canvas.width;
  maskCanvas.height = canvas.height;
  const maskCtx = maskCanvas.getContext("2d", { willReadFrequently: true });
  const maskImage = maskCtx.createImageData(canvas.width, canvas.height);
  detections.forEach((det) => {
    const color = palette[det.id % palette.length];
    for (let i = 0; i < det.mask.length; i += 1) {
      if (!det.mask[i]) continue;
      const px = i * 4;
      maskImage.data[px] = color[0];
      maskImage.data[px + 1] = color[1];
      maskImage.data[px + 2] = color[2];
      maskImage.data[px + 3] = 92;
    }
  });
  maskCtx.putImageData(maskImage, 0, 0);
  ctx.save();
  ctx.filter = "blur(2px)";
  ctx.drawImage(maskCanvas, 0, 0);
  ctx.restore();
  ctx.lineWidth = Math.max(2, canvas.width / 360);
  ctx.font = `${Math.max(14, canvas.width / 44)}px ui-sans-serif`;
  detections.forEach((det) => {
    const color = palette[det.id % palette.length];
    ctx.strokeStyle = `rgb(${color.join(",")})`;
    ctx.fillStyle = ctx.strokeStyle;
    ctx.strokeRect(det.x1, det.y1, det.x2 - det.x1, det.y2 - det.y1);
    ctx.fillText(`id ${det.id} ${det.score ? det.score.toFixed(2) : ""}`, det.x1 + 4, Math.max(18, det.y1 - 6));
  });
  ctx.fillStyle = "rgba(3,5,4,0.72)";
  ctx.fillRect(10, 10, 240, 34);
  ctx.fillStyle = "#f5f7f2";
  ctx.fillText(`client masks ${fmt(elapsed)} ms`, 18, 33);
}

async function getSegSession() {
  if (!window.ort) throw new Error("onnxruntime unavailable");
  if (!state.segSession) {
    setRunState("Loading masks");
    ort.env.wasm.numThreads = Math.min(4, navigator.hardwareConcurrency || 1);
    const modelUrl = "/media/models/yolo11n_sports_roi_sav19_student_320.onnx";
    try {
      state.segSession = await ort.InferenceSession.create(modelUrl, {
        executionProviders: ["webgpu", "wasm"],
        graphOptimizationLevel: "all",
      });
      state.segBackend = navigator.gpu ? "WebGPU or WASM" : "WASM fallback";
    } catch {
      state.segSession = await ort.InferenceSession.create(modelUrl, {
        executionProviders: ["wasm"],
        graphOptimizationLevel: "all",
      });
      state.segBackend = "WASM fallback";
    }
  }
  return state.segSession;
}

function stopBrowserMaskTracking(showVideo = true) {
  state.browserTracking = false;
  if (state.browserTrackHandle) cancelAnimationFrame(state.browserTrackHandle);
  state.browserTrackHandle = null;
  const button = byId("run-browser-masks");
  if (button) {
    button.textContent = "Track masks in browser";
    button.disabled = false;
  }
  if (showVideo) {
    const video = byId("demo-video");
    if (video) video.hidden = false;
    const canvas = byId("browser-canvas");
    if (canvas) canvas.hidden = true;
  }
}

async function runBrowserMaskFrame(session, video) {
  const transform = letterboxToTensor(video, state.segInputSize);
  const inputName = session.inputNames[0];
  const started = performance.now();
  const outputs = await session.run({ [inputName]: transform.input });
  const elapsed = performance.now() - started;
  const detections = decodeSegDetections(
    outputs[session.outputNames[0]],
    outputs[session.outputNames[1]],
    transform,
    video.videoWidth,
    video.videoHeight,
  );
  const tracks = associateBrowserTracks(detections, video.videoWidth, video.videoHeight);
  drawBrowserOverlay(video, tracks, elapsed);
  setText("p95", `${fmt(elapsed, 0)} ms`);
  setText("tracks", `${tracks.length} masks`);
  setLog(`Browser generated ${tracks.length} masks with persistent IDs from this video stream. Last YOLO-Seg frame: ${fmt(elapsed)} ms at ${state.segInputSize} input.`);
}

async function startBrowserMaskTracking() {
  if (state.source === "youtube") {
    setLog("YouTube embeds are cross-origin, so this browser cannot read those frames. Use a sample or uploaded video for client-side masks.");
    return;
  }
  const video = byId("demo-video");
  if (!video.videoWidth) {
    setLog("Wait for the video to load before starting browser mask tracking.");
    return;
  }
  if (state.browserTracking) {
    stopBrowserMaskTracking(true);
    setRunState("Ready");
    setLog("Browser mask tracking stopped.");
    return;
  }
  const button = byId("run-browser-masks");
  button.disabled = true;
  try {
    const session = await getSegSession();
    state.browserTracking = true;
    state.browserTracks = [];
    state.nextBrowserTrackId = 0;
    button.disabled = false;
    button.textContent = "Stop browser masks";
    byId("youtube-frame").hidden = true;
    video.hidden = true;
    byId("browser-canvas").hidden = false;
    setRunState("Client masks");
    setText("fps", "Sports student");
    setText("iou", state.segBackend);
    setLog("Running YOLO-Seg ONNX and mask decoding in this browser with the fast 320 input path.");
    video.play().catch(() => {});
    let lastRun = 0;
    const loop = async (now) => {
      if (!state.browserTracking) return;
      if (!video.paused && now - lastRun > 90) {
        lastRun = now;
        await runBrowserMaskFrame(session, video);
      }
      state.browserTrackHandle = requestAnimationFrame(loop);
    };
    state.browserTrackHandle = requestAnimationFrame(loop);
  } catch {
    stopBrowserMaskTracking(true);
    setRunState("Ready");
    setLog("Browser mask tracking could not start. The segmentation ONNX model may still be loading or this browser may not support the WASM runtime.");
  }
}

async function getYoloSession() {
  if (!window.ort) throw new Error("onnxruntime unavailable");
  if (!state.yoloSession) {
    setRunState("Loading model");
    ort.env.wasm.numThreads = Math.min(4, navigator.hardwareConcurrency || 1);
    state.yoloSession = await ort.InferenceSession.create("/media/models/yolov8n_480_nms.onnx", {
      executionProviders: ["wasm"],
      graphOptimizationLevel: "all",
    });
  }
  return state.yoloSession;
}

async function analyzeCurrentFrame() {
  if (state.source === "youtube") {
    setLog("YouTube embeds are cross-origin, so this browser cannot read their frames. Upload a clip or use the sample video for inference.");
    return;
  }
  const video = byId("demo-video");
  if (!video.videoWidth) {
    setLog("Wait for the video to load before analyzing a frame.");
    return;
  }
  const button = byId("run-browser-onnx");
  button.disabled = true;
  setRunState("Analyzing");
  setLog(`Analyzing one frame with seed prompt: "${state.seedPrompt}"`);
  try {
    await new Promise((resolve) => requestAnimationFrame(resolve));
    const session = await getYoloSession();
    const transform = letterboxToTensor(video);
    const inputName = session.inputNames[0];
    const outputName = session.outputNames[0];
    const started = performance.now();
    const outputs = await session.run({ [inputName]: transform.input });
    const elapsed = performance.now() - started;
    const detections = parseYoloNms(outputs[outputName], transform, video.videoWidth, video.videoHeight);
    const canvas = byId("browser-canvas");
    const ctx = canvas.getContext("2d");
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
    ctx.lineWidth = Math.max(2, canvas.width / 360);
    ctx.font = `${Math.max(15, canvas.width / 42)}px ui-sans-serif`;
    detections.forEach((det, index) => {
      const color = ["#69d16f", "#6fbfe0", "#d8b861", "#dc766e"][index % 4];
      ctx.strokeStyle = color;
      ctx.fillStyle = color;
      ctx.strokeRect(det.x1, det.y1, det.x2 - det.x1, det.y2 - det.y1);
      ctx.fillText(`person ${det.score.toFixed(2)}`, det.x1 + 4, Math.max(18, det.y1 - 6));
    });
    video.hidden = true;
    byId("youtube-frame").hidden = true;
    canvas.hidden = false;
    setRunState("Frame analyzed");
    setLog(`Detected ${detections.length} people in ${fmt(elapsed)} ms. Use Live masks to generate browser-side segmentation overlays.`);
  } catch {
    setRunState("Ready");
    setLog("Browser frame analysis could not start. Try the sample clip, a shorter upload, or live browser masks.");
  } finally {
    button.disabled = false;
  }
}

function wireUpload() {
  const input = byId("upload-video");
  const zone = byId("drop-zone");
  input.addEventListener("change", () => {
    const file = input.files && input.files[0];
    if (file) uploadFile(file);
  });
  ["dragenter", "dragover"].forEach((eventName) => {
    zone.addEventListener(eventName, (event) => {
      event.preventDefault();
      zone.classList.add("dragover");
    });
  });
  ["dragleave", "drop"].forEach((eventName) => {
    zone.addEventListener(eventName, (event) => {
      event.preventDefault();
      zone.classList.remove("dragover");
    });
  });
  zone.addEventListener("drop", (event) => {
    const file = event.dataTransfer.files && event.dataTransfer.files[0];
    if (file) uploadFile(file);
  });
}

document.querySelectorAll(".source-tab").forEach((button) => {
  button.addEventListener("click", () => setSource(button.dataset.source));
});
document.querySelectorAll(".view-button").forEach((button) => {
  button.addEventListener("click", () => setView(button.dataset.view));
});
document.querySelectorAll(".demo-option").forEach((button) => {
  button.addEventListener("click", () => setDemo(button.dataset.demo));
});
byId("apply-prompt").addEventListener("click", () => {
  state.seedPrompt = byId("seed-prompt").value.trim() || "person";
  setLog(`Seed prompt set to "${state.seedPrompt}".`);
});
byId("load-youtube").addEventListener("click", loadYouTube);
byId("run-browser-onnx").addEventListener("click", analyzeCurrentFrame);
byId("run-browser-masks").addEventListener("click", startBrowserMaskTracking);
if (byId("process-upload")) byId("process-upload").addEventListener("click", processUploadOnServer);
wireUpload();
setSource("sample");
